# Generated by Django 3.0.5 on 2020-05-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='nacional_id',
            field=models.CharField(default='', max_length=10, verbose_name="Passenger's nacional id"),
        ),
    ]
